### ISSUE TITLE
tests should only be run against the associated handler

### ISSUE THREAD

**Issue by numberMumbler** [servo/highfive#117]
currently, handlers' tests are not isolated: every handler is run for each test. This causes problems (for example) when checking comment counts in a test result, because multiple handlers might add comments

**Comment by jdm** [comment]
We could probably support this by making `get_handlers` take an argument that is used to filter the resulting handlers that are discovered?

**Comment by numberMumbler** [comment]
I ended up adding it to the test setup, since both the handler and test were accessible at that point. Let me know if you'd like any changes
