### ISSUE TITLE
It's mine, I made a PR for the issue.

### ISSUE THREAD

**Issue by Coder206** [servo/highfive#155]
I noticed a few issues I am actively working on are labelled as "Potentially Open Issues" based on the issue's post last message. However, mine are seen to be more active in the PR. I was thinking it would be great to take this into consideration. Perhaps @highfive can add a tag to an issue saying PR submitted? (C-has-open-PR)

**Comment by jdm** [comment]
I think the effort required to implement this (ie. parsing text of PRs and guessing if it is intended to fix a particular issue if a number is present) isn't worth the reward here. It's not a big deal for project members to add the labels manually when a PR is taking longer to merge than two weeks after the last issue comment.
