### ISSUE TITLE
Cap number of files that are listed in "heads up" comment

### ISSUE THREAD

**Issue by jdm** [servo/highfive#175]
We should list the first five files, followed by "and N more".

**Comment by jdm** [comment]
Code: https://github.com/servo/highfive/blob/master/handlers/watchers/__init__.py

**Comment by pyfisch** [comment]
@highfive: assign me

**Comment by pyfisch** [comment]
Huhu?

@highfive: assign me

**Comment by jdm** [comment]
This repository doesn't have the "C-assigned" label present.
