### ISSUE TITLE
Automatically label saltfs PRs with `S-needs-deploy` when merged

### ISSUE THREAD

**Issue by aneeshusa** [servo/highfive#179]
I just [added](https://github.com/servo/saltfs/issues/658#issuecomment-299940395) a new `S-needs-deploy` label to saltfs to help keep track of what's been deployed on our builders and what hasn't. I'd like this label to be automatically applied when a saltfs PR is merged (to be removed by hand after deploying). Since this is specific to just us, what would be a good way to add this to highfive?

**Comment by jdm** [comment]
Ooh, this is a good idea.

**Comment by jdm** [comment]
https://github.com/servo/highfive/blob/5a21c889cdcdc67df06aa5fc62ddea70e901e963/handlers/status_update/__init__.py#L39 is the hook that runs for all repositories right now. I don't think we have any per-repository handler support right now, but we could theoretically add config file settings to control that [here](https://github.com/servo/highfive/blob/master/eventhandler.py#L63).
