### ISSUE TITLE
test issue

### ISSUE THREAD

**Issue by jdm** [servo/highfive#183]
hi

**Comment by wafflespeanut** [comment]
@highfive[bot] assign me

**Comment by jdm** [comment]
@highfive[bot]: assign me

**Comment by jockehewh** [comment]
hi all ! i'm learning Rust, and familiar with Javascript, how can i contribute ?

**Comment by wafflespeanut** [comment]
Hi! I'm afraid we don't have any stuff in JS to work on, but there's servo/servo#16840 which is an easy issue.

**Comment by wafflespeanut** [comment]
(closing the test issue)
