### ISSUE TITLE
add unassign to hivefive

### ISSUE THREAD

**Issue by tigercosmos** [servo/highfive#199]
we can assign ourselves, but we can't unassign later when we find cannot handle the issue.

**Comment by KiChjang** [comment]
I'm unclear on the benefits of this would have over commenting "please unassign me from this issue" and then have a reviewer remove the tag.

**Comment by tigercosmos** [comment]
yeah. We can let reviewer to do that. But if the bot can do, why not? :)

**Comment by KiChjang** [comment]
Because the bot cannot do what you think it does, the tag does not carry any information about who said `@highfive assign me` before, and if you implement it naively, the bot would just remove the tag whenever someone comments `@highfive unassign me`.

**Comment by tigercosmos** [comment]
@KiChjang  You are right ..
This still can be solve by checking comment above, but it will be too complicated.

**Comment by wafflespeanut** [comment]
@tigercosmos This would be an interesting feature for [the new highfive](https://github.com/servo-automation/highfive/) ([which tracks assignees](https://github.com/servo-automation/highfive/blob/master/cgi-bin/handlers/issues/easy_assign/__init__.py#L102)).

**Comment by tigercosmos** [comment]
@wafflespeanut  Ah! What's the new highfive?
Will it replace the current one soon?

**Comment by wafflespeanut** [comment]
@tigercosmos It was planned for a replacement last year, but it's currently being blocked on an issue with Github itself. Once that's resolved, we'll switch to it :)

I also need to clean it up a bit - right now, it's a giant monolithic hog'ish nightmare which just works.

**Comment by tigercosmos** [comment]
I see. Once it launch, I would like to contribute on it. :)

**Comment by wafflespeanut** [comment]
Sure thing!
