### ISSUE TITLE
Check initial PR description for reviewer

### ISSUE THREAD

**Issue by jdm** [servo/highfive#41]
This requires adding the `on_pr_opened` hook to https://github.com/servo/highfive/blob/master/handlers/assign_reviewer/__init__.py to process the description as well.

**Comment by rundrop1** [comment]
The necessary function to add is `on_pr_opened` https://github.com/servo/highfive/blob/master/handlers/welcome/__init__.py#L7

**Comment by rundrop1** [comment]
Claiming this issue.

**Comment by magni-** [comment]
Claiming this one, assuming @rundrop1 is no longer working on it?

**Comment by rundrop1** [comment]
Go for it!

#40 is part of the same function and you can probably find more info from jdm in that Issue as well.
