### ISSUE TITLE
Warn on adding new files to tests/ref

### ISSUE THREAD

**Issue by jdm** [servo/highfive#42]
We're trying to remove this test harness, but there are a couple tests still running in it. This warning requires looking at the lines of the diff and looking for a before path of `/dev/null` and an after path that includes `tests/ref`. This requires creating a new handler in `handlers/`.

**Comment by Ms2ger** [comment]
I'm hopeful this will all be gone in the next couple of weeks, fwiw.

**Comment by jdm** [comment]
No longer necessary after https://github.com/servo/servo/pull/9293.
