### ISSUE TITLE
Warn if non-ini files are added to tests/wpt/metadata/ or tests/wpt/mozilla/meta/

### ISSUE THREAD

**Issue by jdm** [servo/highfive#43]
This would entail a new handler which looks at the new PR's diff (via `get_diff` in `on_new_pr`), finds a before path of `/dev/null`, and an after path that matches one of the metadata directory paths with a file extension that is not `.ini`.

**Comment by g-k** [comment]
hrm, this should ignore changes to `MANIFEST.json` as in https://github.com/servo/servo/pull/9737

**Comment by jdm** [comment]
Yeah, that's #59.
