### ISSUE TITLE
Add TestBinding.webidl and testbinding.rs to the test check

### ISSUE THREAD

**Issue by emilio** [servo/highfive#49]
Actually if you modify script code you can also add tests to these files:

 * `components/script/dom/testbinding.rs`
 * `components/script/dom/webidls/TestBinding.webidl`

Right now highfive warns you even though you've added tests there (see https://github.com/servo/servo/pull/9304) for example.

Should be easy to check if these files are modified too to prevent the false warning.

**Comment by jdm** [comment]
This is the `missing_tests` handler, for the record.
