### ISSUE TITLE
highfive seems to be changing pr assignees at random points

### ISSUE THREAD

**Issue by samlh** [servo/highfive#69]
For example, see:
https://github.com/servo/servo/pull/10085#event-597965935

**Comment by jdm** [comment]
That's super weird. The only calls to `api.set_assignee` are from `handlers/assign_reviewer/__init__.py`, and those come from `on_new_pr` and `on_new_comment`, and there's no reason I can see for the assignee to be updated based on the activity in that PR.

**Comment by zwn** [comment]
I guess there might have been a comment requesting the assignment but later got deleted. Can this be verified or is the deletion without a trace?

**Comment by jdm** [comment]
I don't know of any log that could be verified.

**Comment by jdm** [comment]
Haven't seen this or a long time.
