### ISSUE TITLE
Support file path exclusions in watcher handler

### ISSUE THREAD

**Issue by jdm** [servo/highfive#76]
#46 added file path watching, but we should support exclusions as well. This list would be checked after finding a match in `handlers/watchers/__ini__.py` and it would be ignored if there's a matching exclusion found. I propose that any path for a particular user that starts with a `-` should be considered an exclusion (`jdm = foo/blah -foo/blah/bar`)

**Comment by Mylainos** [comment]
I would like to take this one please !

**Comment by jdm** [comment]
Go ahead!

**Comment by Mylainos** [comment]
What should be done in that case:
```
jdm = forbiden_dir/whatched_file -forbiden_dir/
```

**Comment by jdm** [comment]
Any changes to `whatched_filed` sould be ignored according to that rule.

**Comment by jdm** [comment]
Fixed by #76.
