### ISSUE TITLE
Report a warning for diffs containing `<title></title>`

### ISSUE THREAD

**Issue by jdm** [servo/highfive#85]
This usually indicates a new test file being created without appropriate metadata. We should point this out! This should live in a new handler in `handlers`, but it can use the `unsafe` handler as inspiration.

**Comment by torbjorntorbjorn** [comment]
I've created pull request #97, which has a new handler that checks for the empty title elements.
The check is quite naive for now, but will hopefully be useful.

**Comment by Wafflespeanut** [comment]
fixed by #97
