### ISSUE TITLE
Unescape HTML when reading test expectations

### ISSUE THREAD

**Issue by emilio** [servo/highfive#94]
Right now if the comment contains HTML, it's sent to github escaped, which makes things like the `&#39;new&#39;` you see in https://github.com/servo/servo/pull/10819#issuecomment-213735708 appear.

**Comment by Ms2ger** [comment]
We should not be reading HTML at all, now that we have structured logs with a summary of the errors.

**Comment by Wafflespeanut** [comment]
That was the original intent, but [we don't have all the necessary info in the structured log](https://github.com/servo/highfive/pull/86#issue-150127369) - currently, it shows only the test name and the expected & unexpected results (along with a lot of `stackwalk_stdout` stuff).

**Comment by Wafflespeanut** [comment]
We can use the built-in `HTMLParser` for doing the unescaping.

**Comment by Nebopolis** [comment]
I would like to work on this issue.

**Comment by Wafflespeanut** [comment]
Great to know! Please go ahead :)
